In [2]:
import pyGM as gm
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline 
f1 = np.ones((3,3))
f2 = np.ones((3,3))
f3 = np.ones((3,3))
f4 = np.ones((3,3))
p1 = np.array([[0.249,0.002,0.311],
[0.017,0.024,0.015],
[0.029,0.348,0.000]])
p2 = np.array([[0.136,0.118,0.309],
[0.003,0.029,0.025],
[0.348,0.014,0.015]]
)
p3 = np.array([[0.008,0.014,0.274],
[0.351,0.024,0.000],
[0.129,0.123,0.074]] 
)
p4 = np.ones((3,3))
xy = np.ones((4,4,3,3))
xy[0,1,:]=p1
xy[1,2,:]=p2
xy[2,3,:]=p3
xy[0,3,:]=p4
xy[1,3,:]=p4
xy[0,2,:]=p4
edge = np.array([[0,1],[1,2],[2,3],[0,3],[1,3],[0,2]])

In [3]:
X = [gm.Var(i,3) for i in range(4)] 
factor = [gm.Factor([X[0],X[1]],1.0) , gm.Factor([X[1],X[2]],1.0) , gm.Factor([X[2],X[3]],1.0),
          gm.Factor([X[0],X[3]],1.0) , gm.Factor([X[1],X[3]],1.0) , gm.Factor([X[0],X[2]],1.0)]

In [4]:
for i in range(len(factor)):
    factor[i].table = np.ones((3,3))
maxiterations = 1
like = np.zeros((maxiterations,))
it = 0
while (it < maxiterations):
    for i in range (0,len(edge)):
        print(edge[i])
        model = gm.GraphModel(factor)
        pri = [1.0 for Xi in X]
        #print(i[0],i[1])
        a = int(edge[i][0])
        b = int(edge[i][1])
        pri[a], pri[b] = 2.0,2.0          # eliminate X1 and X3 last
        #print(pri)
        order = gm.eliminationOrder(model, orderMethod='minfill', priority=pri)[0]
        ###print (order,'\n')

        sumElim = lambda F,Xlist: F.sum(Xlist)   # helper function for eliminate
        model.eliminate(order[:-2], sumElim)  # eliminate all but last two

        p13 = model.joint()
        lnZ = np.log(p13.sum())   # can get the (log) partition function as well
        ###print ('lnZ: ',lnZ,'\n')
        p13 /= p13.sum()
        ###print (p13, '\n',p13.table)
        #print(a,b)
        #print(xy[a,b,:])
        #print(xy[a,b,:]/p13.table)
        #print(factor[i].table*(xy[a,b,:]/p13.table))
        factor[i].table = factor[i].table*(xy[a,b,:]/p13.table)
    it += 1
  

[0 1]
Factor({0,1})
adding factor in var:  1 

Factor({0,1}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
adding factor in var:  0 

Factor({0,1}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Factor({1,2})
adding factor in var:  2 

Factor({1,2}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
adding factor in var:  1 

Factor({1,2}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Factor({2,3})
adding factor in var:  3 

Factor({2,3}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
adding factor in var:  2 

Factor({2,3}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Factor({0,3})
adding factor in var:  3 

Factor({0,3}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
adding factor in var:  0 

Factor({0,3}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Factor({1,3})
adding factor in var:  3 

Factor({1,3}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
adding factor in var:  1 

Factor({1,3}) [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Factor({0,2})
adding factor in var:  2 

Factor({0,2})